services:
  postgres:
    container_name: arnoldSpringJdbc
    image: postgres
    environment:
      POSTGRES_USER: arnold
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5462:5432"
#      - host:external
    networks:
      - postgres
    restart: unless-stopped
  demo:
    container_name: arnold-api
    image: atambwe/demo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
      - "8088:3000"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadminArnoldJdbc
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: